version: "3.9"
   
services:
  web:
    container_name: web
    build: .
    environment:
      - DB_DRIVER=django.db.backends.postgresql
      - PG_NAME=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PG_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}