version: "3.9"
   
services:
  web:
    container_name: web
    image: francescoxx/django-docker:1.0.0
    build: .
    environment:
      - DB_DRIVER=django.db.backends.postgresql
      - PG_DATABASE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_HOST=database-1.c9nq6suhmqou.us-east-1.rds.amazonaws.com
      - PG_PORT=5432
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}